services:
  postgres:
    image: postgres:15
    container_name: postgres_tp2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: unless-stopped

  elasticsearch:
    image: elasticsearch:8.12.0
    container_name: guilda-es
    ports:
      - "9200:9200"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      discovery.type: "single-node"
      xpack.security.enabled: "false"
    deploy:
      resources:
        limits:
          memory: 2g

  redis:
    image: redis:7-alpine
    container_name: guilda-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  app:
    build: .
    container_name: guilda-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - elasticsearch
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_ELASTICSEARCH_URIS: http://elasticsearch:9200
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    restart: unless-stopped
