-- ================================================
-- Schema de teste H2 - compatível com PostgreSQL
-- ================================================

-- Schema AUDIT (sistema legado)
CREATE SCHEMA IF NOT EXISTS audit;
CREATE SCHEMA IF NOT EXISTS aventura;

-- Organizações
CREATE TABLE IF NOT EXISTS audit.organizacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) UNIQUE NOT NULL,
    ativo BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Usuários
CREATE TABLE IF NOT EXISTS audit.usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacao_id BIGINT NOT NULL,
    nome VARCHAR(255),
    email VARCHAR(255),
    senha_hash VARCHAR(255),
    status VARCHAR(50),
    ultimo_login_em TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_usuario_org_email UNIQUE (organizacao_id, email),
    CONSTRAINT fk_usuario_organizacao FOREIGN KEY (organizacao_id) REFERENCES audit.organizacoes(id)
);

-- Roles
CREATE TABLE IF NOT EXISTS audit.roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacao_id BIGINT NOT NULL,
    nome VARCHAR(255),
    descricao VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_role_org_nome UNIQUE (organizacao_id, nome),
    CONSTRAINT fk_role_organizacao FOREIGN KEY (organizacao_id) REFERENCES audit.organizacoes(id)
);

-- Permissions
CREATE TABLE IF NOT EXISTS audit.permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255) UNIQUE,
    descricao VARCHAR(255)
);

-- Tabela de junção Usuarios <-> Roles
CREATE TABLE IF NOT EXISTS audit.user_roles (
    usuario_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    granted_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (usuario_id, role_id),
    CONSTRAINT fk_ur_usuario FOREIGN KEY (usuario_id) REFERENCES audit.usuarios(id),
    CONSTRAINT fk_ur_role FOREIGN KEY (role_id) REFERENCES audit.roles(id)
);

-- Tabela de junção Roles <-> Permissions
CREATE TABLE IF NOT EXISTS audit.role_permissions (
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_rp_role FOREIGN KEY (role_id) REFERENCES audit.roles(id),
    CONSTRAINT fk_rp_permission FOREIGN KEY (permission_id) REFERENCES audit.permissions(id)
);

-- API Keys
CREATE TABLE IF NOT EXISTS audit.api_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacao_id BIGINT NOT NULL,
    nome VARCHAR(255),
    key_hash VARCHAR(255),
    ativo BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    last_used_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_api_key_org_nome UNIQUE (organizacao_id, nome),
    CONSTRAINT fk_api_key_organizacao FOREIGN KEY (organizacao_id) REFERENCES audit.organizacoes(id)
);

-- Audit Entries
CREATE TABLE IF NOT EXISTS audit.audit_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacao_id BIGINT,
    actor_user_id BIGINT,
    actor_api_key_id BIGINT,
    action VARCHAR(255),
    entity_schema VARCHAR(255),
    entity_name VARCHAR(255),
    entity_id VARCHAR(255),
    occurred_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ip VARCHAR(50),
    user_agent VARCHAR(255),
    diff CLOB,
    metadata CLOB,
    success BOOLEAN,
    CONSTRAINT fk_audit_organizacao FOREIGN KEY (organizacao_id) REFERENCES audit.organizacoes(id),
    CONSTRAINT fk_audit_user FOREIGN KEY (actor_user_id) REFERENCES audit.usuarios(id),
    CONSTRAINT fk_audit_api_key FOREIGN KEY (actor_api_key_id) REFERENCES audit.api_keys(id)
);

-- ================================================
-- Schema AVENTURA (domínio novo)
-- ================================================

-- Aventureiros
CREATE TABLE IF NOT EXISTS aventura.aventureiros (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacao_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    nome VARCHAR(120) NOT NULL,
    classe VARCHAR(255) NOT NULL,
    nivel INT NOT NULL CHECK (nivel >= 1),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_aventureiro_organizacao FOREIGN KEY (organizacao_id) REFERENCES audit.organizacoes(id),
    CONSTRAINT fk_aventureiro_usuario FOREIGN KEY (usuario_id) REFERENCES audit.usuarios(id)
);

-- Companheiros
CREATE TABLE IF NOT EXISTS aventura.companheiros (
    aventureiro_id BIGINT PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    especie VARCHAR(255) NOT NULL,
    indice_lealdade INT NOT NULL CHECK (indice_lealdade >= 0 AND indice_lealdade <= 100),
    CONSTRAINT fk_companheiro_aventureiro FOREIGN KEY (aventureiro_id) REFERENCES aventura.aventureiros(id) ON DELETE CASCADE
);

-- Missões
CREATE TABLE IF NOT EXISTS aventura.missoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacao_id BIGINT NOT NULL,
    titulo VARCHAR(150) NOT NULL,
    nivel_perigo VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_inicio TIMESTAMP WITH TIME ZONE,
    data_termino TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_missao_organizacao FOREIGN KEY (organizacao_id) REFERENCES audit.organizacoes(id)
);

-- Participações em Missão
CREATE TABLE IF NOT EXISTS aventura.participacoes_missao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    missao_id BIGINT NOT NULL,
    aventureiro_id BIGINT NOT NULL,
    papel VARCHAR(255) NOT NULL,
    recompensa_ouro NUMERIC(19, 2) DEFAULT 0,
    destaque BOOLEAN NOT NULL DEFAULT FALSE,
    data_registro TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_participacao_missao FOREIGN KEY (missao_id) REFERENCES aventura.missoes(id) ON DELETE CASCADE,
    CONSTRAINT fk_participacao_aventureiro FOREIGN KEY (aventureiro_id) REFERENCES aventura.aventureiros(id) ON DELETE CASCADE,
    CONSTRAINT uk_participacao_missao_aventureiro UNIQUE (missao_id, aventureiro_id)
);
